weather:
  api:
    url: http://api.openweathermap.org/data/2.5/weather
    app-id:
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherdb
    username: username
    password: password
management:
  endpoints:
    web:
      exposure:
        include: health,env,metrics,logfile,info
info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@