weather:
  api:
    url: ${APP_URL}
    app-id: ${APP_ID}
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/weatherdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}